###### 1D Array (One-Dimensional Array)
A 1D array is the simplest form of an array, containing a single sequence of elements in a straight line. 
You can think of it as a list of items.

Shape: (n,) where n is the number of elements.
Example: A 1D array with five elements [10, 20, 30, 40, 50] has the shape (5,).

In [1]:
import numpy as np
array_1D = np.array([10,20,30,40,50])
print("\n1D array", array_1D)
print("\nshape array", array_1D.shape)
print("\ndata type of Array", array_1D.dtype)
print("\ndimension of Array", array_1D.ndim)


1D array [10 20 30 40 50]

shape array (5,)

data type of Array int32

dimension of Array 1


###### 2D Array (Two-Dimensional Array)
A 2D array represents a grid of values, arranged in rows and columns, similar to a table or matrix.

Shape: (m, n) where m is the number of rows, and n is the number of columns.

Example: A 2D array with three rows and two columns could look like this:

This array has two axes:

Axis 0 (rows): 3 rows.
Axis 1 (columns): 2 columns.
A 2D array is often used in data tables, images (grayscale), and matrices.


In [3]:
array_2D = np.array([[1,2], [3,4]])
print("\n2D array\n", array_2D)
print("\nshape array", array_2D.shape)
print("\ndata type of Array", array_2D.dtype)
print("\ndimension of Array", array_2D.ndim)


2D array
 [[1 2]
 [3 4]]

shape array (2, 2)

data type of Array int32

dimension of Array 2


###### 3D Array (Three-Dimensional Array)
A 3D array is made up of multiple 2D arrays stacked together, forming a cube-like structure. This is often used for collections of images, volumetric data, or sequences of matrices.

Shape: (p, m, n) where:
p is the number of 2D matrices (or layers).
m is the number of rows in each 2D matrix.
n is the number of columns in each 2D matrix.

Example: A 3D array with two layers, each containing a 2x2 grid:
This array has three axes:

Axis 0 (depth): 2 layers.
Axis 1 (rows): 2 rows in each layer.
Axis 2 (columns): 2 columns in each row.
A 3D array can represent multiple grayscale images, 
color images with separate RGB layers, or even volumetric data like MRI scans.


In [4]:
array_3D = np.array([[[1,2],[2,3]], [[4,5], [5,6]], [[7,8], [8,9]]])
print("3D Array\n", array_3D)
print("\nShape of Array", array_3D.shape)
print("\ndata type of Array", array_3D.dtype)
print("\ndimension of Array", array_3D.ndim)

3D Array
 [[[1 2]
  [2 3]]

 [[4 5]
  [5 6]]

 [[7 8]
  [8 9]]]

Shape of Array (3, 2, 2)

data type of Array int32

dimension of Array 3


###### Array with Zero's

In [6]:
a = np.zeros((4,8), dtype = int)
a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
b = np.zeros((4,8), dtype = float)
b

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

###### Array with 1's

In [26]:
c = np.ones((4,8), dtype = int)
c

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

###### diagnol 1's

In [30]:
d = np.eye(5, dtype = int)
d

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

###### a range

In [10]:
e = np.arange(0,20,2)
e

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#Specified step size
arr1 = np.arange(0, 10, step=2)
print(arr1)

[0 2 4 6 8]


###### linspace

In [18]:
j = np.linspace(0.0, 1.0, 11)
print(j)
f = np.linspace(0.0, 1.0, 11, retstep=True, dtype=int)
print(f)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), 0.1)


###### converting float to int

In [14]:
f = np.linspace(0.0, 1.0, 11)
integer_elements = f[f == f.astype(int)]  # Filter only integer values
print(integer_elements.astype(int))

[0 1]


###### np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

start: The starting value of the range.

stop: The end value of the range.

num: The number of samples to generate (default is 50).

endpoint: If True (default), includes the stop value; if False, it excludes it.

retstep: If True, returns a tuple with the array and the spacing between values.

dtype: The desired data type of the resulting array.

###### Excluding the Endpoint

If you want to exclude the stop value (10 in this case):

In [40]:
arr = np.linspace(0, 10, num=5, endpoint=False)
print(arr)

[0. 2. 4. 6. 8.]


###### 3. Getting the Step Size
You can also find out the spacing between each element by setting retstep=True:

In [21]:
arr2, step = np.linspace(0, 10, num=5, retstep=True)
print("Array:", arr2)
print("Step size:", step)

Array: [ 0.   2.5  5.   7.5 10. ]
Step size: 2.5


###### random gives random float values

In [26]:
a_random = np.random.random((10,))
print("\n 1 dimension \n", a_random)
a1_random = np.random.random((3,2))
print("\n 2 dimension \n", a1_random)


 1 dimension 
 [0.15776214 0.67411437 0.23770231 0.81027925 0.08064776 0.92346743
 0.16214541 0.49718742 0.80657627 0.89384366]

 2 dimension 
 [[0.51963003 0.15357177]
 [0.60830278 0.92432988]
 [0.41560055 0.43988593]]


###### ranint gives random integer values

In [31]:
b_random = np.random.randint(0, 10, size = 10)
b_random
e_random = np.random.randint(0, 10, (4,4))
e_random
print(b_random)
print(e_random)

[0 5 2 3 7 1 6 6 6 3]
[[5 9 2 7]
 [0 9 6 7]
 [2 5 8 5]
 [6 7 0 5]]


In [62]:
g_random = 100 * np.random.random((3,2))
g_random

array([[33.86976545, 90.78329956],
       [86.57042001, 92.99816441],
       [19.27512153, 87.45754659]])

###### Indexing and slicing in arrays

In [66]:
g_random[1,1]

92.99816440886758

In [68]:
g_random[0,1]

90.78329955792054

In [32]:
print(e_random)
print(e_random[3, 0:3])

[[5 9 2 7]
 [0 9 6 7]
 [2 5 8 5]
 [6 7 0 5]]
[6 7 0]


In [33]:
print(e_random[3, :3])

[6 7 0]


In [34]:
print(e_random[3, 0:])

[6 7 0 5]


In [82]:
print(e_random[3, :])

[7 6 3 0]


In [36]:
print(e_random[:, 0:3])

[[5 9 2]
 [0 9 6]
 [2 5 8]
 [6 7 0]]


In [38]:
print(e_random[1:, 3])

[7 5 5]


In [40]:
ran_array = np.random.random((3,5))
ran_array

array([[0.42541772, 0.76903771, 0.80202895, 0.00814193, 0.13178068],
       [0.36398066, 0.32712659, 0.33232634, 0.77166911, 0.28127357],
       [0.4989175 , 0.3563999 , 0.96023659, 0.816588  , 0.70754803]])

In [91]:
ran_array > 0.5

array([[ True,  True, False, False, False],
       [False, False, False,  True,  True],
       [ True, False, False,  True,  True]])

In [92]:
ran_array[ran_array>0.5]

array([0.62856599, 0.72983566, 0.78432807, 0.70774341, 0.63653105,
       0.86800226, 0.62112439])

In [41]:
s = np.random.randint(0, 10, (3,3))
s

array([[2, 1, 2],
       [0, 1, 5],
       [2, 6, 1]])

In [42]:
p = np.random.randint(10, 20, (3,3))
p

array([[19, 11, 11],
       [14, 19, 16],
       [17, 13, 13]])

In [43]:
b = s+p
b

array([[21, 12, 13],
       [14, 20, 21],
       [19, 19, 14]])

In [101]:
b = s - p
b

array([[ -9, -10, -12],
       [ -8,  -9, -10],
       [-10,  -8,  -7]])

In [102]:
b = s*p
b

array([[ 90, 119, 133],
       [ 33,  22,  75],
       [171, 105,  44]])

In [104]:
b = s/p
b

array([[0.4       , 0.41176471, 0.36842105],
       [0.27272727, 0.18181818, 0.33333333],
       [0.47368421, 0.46666667, 0.36363636]])

In [44]:
s = np.random.randint(0, 10, (3,4))
s

array([[8, 6, 1, 9],
       [5, 6, 8, 9],
       [9, 0, 4, 2]])

In [49]:
s = np.random.randint(0, 10, (4,3))
print(s)

[[9 3 0]
 [4 1 3]
 [0 0 4]
 [2 9 0]]


In [47]:
np.sum(s)

48

In [50]:
print(np.sum(s, axis = 0))

[15 13  7]


In [51]:
print(np.sum(s, axis = 1))

[12  8  4 11]


In [115]:
print(np.min(s, axis = 0))
print(np.max(s, axis = 0))
print(np.min(s, axis = 1))
print(np.max(s, axis = 1))

[2 0 2]
[9 8 7]
[2 2 0 7]
[4 8 2 9]


In [118]:
print(s)
print(np.mean(s, axis = 0))
print(np.mean(s, axis = 1))
print(np.std(s, axis = 0))
print(np.std(s, axis = 1))

[[3 2 4]
 [6 8 2]
 [2 0 2]
 [9 7 7]]
[5.   4.25 3.75]
[3.         5.33333333 1.33333333 7.66666667]
[2.73861279 3.34477204 2.04633819]
[0.81649658 2.49443826 0.94280904 0.94280904]


In [56]:
n = np.array([[1,1,2], [2,3,4], [3,5,7]])
n

array([[1, 1, 2],
       [2, 3, 4],
       [3, 5, 7]])

In [57]:
np.unique(n)

array([1, 2, 3, 4, 5, 7])

In [58]:
np.reshape(n, (9,))

array([1, 1, 2, 2, 3, 4, 3, 5, 7])

In [61]:
np.reshape(n, (3,3))

array([[1, 1, 2],
       [2, 3, 4],
       [3, 5, 7]])

In [62]:
np.transpose(n)

array([[1, 2, 3],
       [1, 3, 5],
       [2, 4, 7]])

##### excercise

In [130]:
import numpy as np
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
print(a)

lastrow=a[-1]
print(lastrow)
print(type(lastrow))

firstcol= a[:,0]
print(firstcol)
print(len(firstcol))
a_gt_5=a>5
print(a_gt_5)


elements_gt_5 = a[a_gt_5]

print(elements_gt_5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
<class 'numpy.ndarray'>
[0 4 8]
3
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]


In [131]:
import numpy as np

x = np.arange(10,20)
y = np.linspace(0.,1.,10)
z = np.arange(0,10).reshape((5,2))

print(x)
print(y)
print(z)

a = x+x
b=z/100
c=x*y

w1=np.sum(z,axis=0)
w2=np.sum(z,axis=1)
zmean =np.mean(z)

[10 11 12 13 14 15 16 17 18 19]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


###### array tip sheet in downloads folder